##
## EPITECH PROJECT, 2024
## B-YEP-400-TLS-4-1-zappy-leo.wehrle [WSL: Ubuntu]
## File description:
## Makefile
##


all:

zappy_gui:
	@echo -e "do nothing"

clean:
	@echo -e "cleaning"

fclean:
	@echo -e "deep cleaning"

re: fclean all

.PHONY: all zappy_gui clean fclean re
