##
## EPITECH PROJECT, 2024
## B-YEP-400-TLS-4-1-zappy-leo.wehrle [WSL: Ubuntu]
## File description:
## Makefile
##


all: zappy_ai

zappy_ai:
	@echo -e "do nothing"
	echo "zappy_ai" > zappy_ai

clean:
	@echo -e "cleaning"

fclean:
	@echo -e "deep cleaning"

re: fclean all

.PHONY: all zappy_ai clean fclean re
.NOTPARALLEL: re
