##
## EPITECH PROJECT, 2024
## Zappy
## File description:
## Makefile
##

SRC =	main.py

NAME = zappy_ai

$(NAME):
	cp $(SRC) $(NAME)
	chmod +x $(NAME)

all:	$(NAME)

fclean:
	rm -f $(NAME)

re: fclean all

.PHONY: all fclean re
